### PR TITLE
Download/upload of recent changes (changelogs)

### PR DESCRIPTION
**Pull request by lurbas**
- Downloading recent changes and storing them in 'changelogs' directory during the 'init' process.
- Uploading changelog from .txt file. Name of the file needs to match apk's code version.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Looks great, thanks for the pull request. Can you run `rubocop -a` to fix some of the code styling issues? 
Have you tested the changes for your setup?

**Comment by lurbas** [comment]
Sorry for late response. I've fixed some styling issues with rubocop.
Yes, I've tested it for my setup. Both download and upload process work fine for me. But please take a closer look at it, because that's my first code in ruby.

**Comment by juanramon** [comment]
When it could be merged @KrauseFx? :smile:

**Comment by KrauseFx** [comment]
These are a lot of changes in the architecture of how `supply` works. Could you briefly explain on what you changed, why you changed it and how it's different from the user's perspective?

**Comment by lurbas** [comment]
I don’t think there are a lot of changes in architecture. I've just added what I've thought was necessary. Let me explain.
During the `setup` process I’m getting the list of all apk **version codes** from store api.
Next, iterating through this list I’m getting specific changelog in all languages.
Everything is saved in .txt files following previous convention:
`metadata/android/{language}/changelogs/{version_code}.txt`
From user's perspective, there is a new directory `changelogs` with list of files containg recent changes from the store.
During the `supply` process, after successfully uploaded the binary file I’m returning **version code** of the apk. Then, I’m looking for changelog with the name equal to this new **version code**. If exists, I'm sending request with content from the .txt file.
From user's perspective: before executing `supply`, he/she needs to add a new .txt file in `changelogs` directory. Name of the file needs to match with apk **version code** of the new build.

**Comment by asfalcone** [comment]
@lurbas Thanks for contributing this! I've done some local testing and found it to work well. The biggest thing I am wondering about is the introduction of version code into the structure of the metadata folder. Other things like images and screenshots get uploaded just as they are in the directory, regardless of what version they are intended for. I like the notion of versioning things, but I think it seems out of place to version the changelogs and nothing else.

**Comment by asfalcone** [comment]
@lurbas actually I've thought about this and tested it out more and I am going to take back my previous comment about version codes seeming out of place. I also tested out using multiple languages and it works great. Could you squash the commits down to 1 and I think we'll be ready to merge! :grinning:

**Comment by asfalcone** [comment]
@lurbas looks like you picked up a few extra commits and have some conflicts. try rebasing on master then squashing to get back to a good place.

**Comment by lurbas** [comment]
I hope it's fine right now, and I haven't lost anything in the process

**Comment by harikishan7** [comment]
This is a great feature and hope you can release this out soon. Been waiting on this since a long time. Could you provide the usage for this ?

**Comment by asfalcone** [comment]
@lurbas thanks for all the effort on this one! this is great. 🚀

**Comment by lurbas** [comment]
@asfalcone thank you too. I'm happy it's finally in production :)

**Comment by asfalcone** [comment]
@harikishan7 We'll do a release with this feature soon! Can you review the documentation here https://github.com/fastlane/supply/pull/34?

**Comment by asfalcone** [comment]
Resolves #2

**Comment by emidander** [comment]
Nice, this is something I really wanted!

**Pull request merged**
